File IO: File open/save dialog utility functions
Hourglass-Resurrection/Hourglass-Resurrection pull request #61
Opened 2017-05-24 12:21 UTC by Scepheo

PR to create and use utility functions for the file open/save dialog, in a more "C++ way" than the current code.

2017-05-24 12:30 UTC, YaLTeR commented on source/application/AVIDumping/AVIDumper.cpp
> + * Copyright (c) 2017 - Hourglass Resurrection Team
Pretty sure this should be 2015-2017.

2017-05-24 12:30 UTC, YaLTeR commented on source/application/utils/File.h
> +            const std::string location,
You might've meant to pass all these by const reference, in which case you forgot the &.

2017-05-24 12:30 UTC, YaLTeR commented on source/application/utils/file/Path.cpp
> +    return last_slash == std::string::npos ? std::string() : path.substr(0, last_slash);
This won't work the same on `C:\Folder\` vs. `C:\Folder`, is that the intended behaviour?

2017-05-24 12:30 UTC, YaLTeR commented on source/application/wintaser.cpp
> +    if (avi_file_name == "")
I think `avi_file_name.empty()` would  be clearer here.

2017-05-24 16:25 UTC, Warepire commented on source/application/AVIDumping/AVIDumper.cpp
> + * Copyright (c) 2017 - Hourglass Resurrection Team
That should have remained simply "2015-".

2017-05-24 16:36 UTC, Warepire requested changes

2017-05-24 16:36 UTC, Warepire commented on source/application/AVIDumping/AVIDumper.h
> + * Copyright (c) 2017 - Hourglass Resurrection Team
Incorrect, copyrights don't update like this. Should remain at "2015-".

2017-05-24 16:36 UTC, Warepire commented on source/application/Config.cpp
> + * Copyright(c) 2017 - Hourglass Resurrection Team
Should probably say "2015-", since it's an older file.

2017-05-24 16:36 UTC, Warepire commented on source/application/Config.h
> + * Copyright(c) 2017 - Hourglass Resurrection Team
Same here, 2015.

2017-05-24 16:36 UTC, Warepire commented on source/application/utils/file/FileDialog.cpp
> +    std::map<Utils::File::FileFilter, const char*> gs_file_type_map =
Not static, nor global.

2017-05-24 16:36 UTC, Warepire commented on source/application/utils/file/FileDialog.cpp
> +        for (auto file_type : file_types)
`auto&`, ensures you're using references and not copies.

2017-05-24 16:36 UTC, Warepire commented on source/application/utils/file/Path.cpp
> +std::string Utils::File::GetFileName(const std::string path)
I've been thinking about this, what about a class called `Path` that inherits `std::string`?

2017-05-24 16:36 UTC, Warepire commented on source/application/utils/file/Path.cpp
> +    return last_slash == std::string::npos ? std::string() : path.substr(0, last_slash);
I believe this was broken also in the original code.

2017-05-24 16:36 UTC, Warepire commented on source/application/wintaser.cpp
> +    if (avi_file_name == "")
Yes.

2017-05-24 16:36 UTC, Warepire commented on source/application/wintaser.cpp
> +
Lot's of whitespace for no reason.

2017-05-25 17:10 UTC, Scepheo commented on source/application/utils/file/Path.cpp
> +    return last_slash == std::string::npos ? std::string() : path.substr(0, last_slash);
@Warepire not broken, intended behaviour. `C:\Folder\` is the folder called `Folder` under `C:`, `C:\Folder` is the file called `Folder`. Same goes for `GetFileName`; this is simply how Windows deals with paths.

2017-05-26 15:49 UTC, Scepheo commented on source/application/utils/file/Path.cpp
> +std::string Utils::File::GetFileName(const std::string path)
Not entirely sure what you mean, do you just want extra type safety?

2017-05-27 09:18 UTC, Warepire commented on source/application/utils/file/Path.cpp
> +    return last_slash == std::string::npos ? std::string() : path.substr(0, last_slash);
Right. We might need some sugar on top for any prompt where we should pick a path later.

2017-05-27 09:21 UTC, Warepire commented on source/application/utils/file/Path.cpp
> +std::string Utils::File::GetFileName(const std::string path)
I mean, `class Path : public std::string` that gives all the functionality of string (and can be passed as a string if we don't add member variables), but with these additional functions to get directory and file name from the class.

2017-06-04 14:53 UTC, Warepire commented on .gitignore
> +.vs/
This could preferably be it's own commit.

2017-06-04 14:55 UTC, Warepire requested changes

2017-06-04 14:55 UTC, Warepire commented on source/application/utils/file/Path.cpp
> +std::string Utils::File::GetFileName(const std::string& path)
I'm still interested in discussing whether the Path utils should be a class inheriting from `std::string` and these being additional member functions.

2017-07-27 16:05 UTC, Scepheo commented
Due to the move to C++17 and VS2017, I'll be dropping this PR and seeing if the changes still apply. If they do, I'll open a new PR to merge them.

2017-07-27 16:05 UTC, closed without merging