File IO: File open/save dialog utility functions
Hourglass-Resurrection/Hourglass-Resurrection pull request #65
Opened 2017-07-27 17:44 UTC by Scepheo

Repeat of [PR 61](https://github.com/Hourglass-Resurrection/Hourglass-Resurrection/pull/61), as it turns out these changes still apply after the switch to C++17.

2017-07-27 19:43 UTC, Warepire requested changes

2017-07-27 19:43 UTC, Warepire commented on source/application/ramwatch.cpp
>  int Change_File_S(char *Dest, const char *Dir, const char *Titre, const char *Filter, const char *Ext, HWND hwnd)
Many of these params are never used now, perhaps reduce their signatures?

2017-07-27 19:43 UTC, Warepire commented on source/application/ramwatch.cpp
>  int Change_File_L(char *Dest, const char *Dir, const char *Titre, const char *Filter, const char *Ext, HWND hwnd)
Same here.

2017-07-27 19:43 UTC, Warepire commented on source/application/utils/file/FileDialog.cpp
> +std::string Utils::File::GetFileNameOpen(
Oh the code duplication between Open and Save. Can you consolidate this? Perhaps with an `enum class` to pick Open or Save?

2017-07-28 16:39 UTC, Warepire requested changes

2017-07-28 16:39 UTC, Warepire commented on source/application/utils/file/FileDialog.cpp
> +        const FileNameGetter get)
Rename `get` to something more clear, like `file_name_getter`.

2017-07-28 16:39 UTC, Warepire commented on source/application/utils/file/FileDialog.cpp
> +    typedef BOOL(WINAPI FileNameGetter)(LPOPENFILENAME open_file_name);
Use `using`.

2017-07-28 17:10 UTC, Warepire commented
Please validate that it still works, and once it does, please squash the commits.

Code looks good to me.

2017-07-28 23:11 UTC, Scepheo commented
It works on my machine.

Verified, it appears to still work as before. I squashed the commits, feel free to merge the PR if you see fit.

2017-07-29 13:18 UTC, Warepire approved these changes

2017-07-29 13:19 UTC, merged