EXE & DLL: Major logging overhaul
Hourglass-Resurrection/Hourglass-Resurrection pull request #75
Opened 2017-08-18 19:34 UTC by Warepire

This turns the logging process of Hourglass more C++ like, and the DLL gets a more binary-like logging format under the hood, which removes the need for `swprintf`.

2017-08-18 19:42 UTC, Warepire commented
Keep note that now when building debug builds the Output tab in Visual Studio will get a bit spammy, since the debug levels where dropped.

2017-08-18 19:56 UTC, YaLTeR requested changes

2017-08-18 19:56 UTC, YaLTeR commented on source/application/logging.cpp
> +                    m_buffer << *reinterpret_cast<const unsigned long long int*>(data);
`const unsigned short` but `const unsigned long long int`. I suggest dropping `int`.

2017-08-18 19:56 UTC, YaLTeR commented on source/application/logging.cpp
> +        data += size + (4 - (size % 4));
This will do `data += size + 4` if `size == 4` or `size == 0`, while it should do just `data += size`?

2017-08-18 19:56 UTC, YaLTeR commented on source/shared/ipc.h
> +            m_pos += (sizeof(DWORD) * 2) + length + (4 - (length % 4));
Same thing for `length == 4` and `lenght == 0` as  above.

2017-08-18 19:56 UTC, YaLTeR commented on source/shared/ipc.h
> +            if (m_pos >= ARRAYSIZE(m_message) - length)
This should probably be `- length - 8` for the metadata.

2017-08-18 19:56 UTC, YaLTeR commented on source/shared/ipc.h
> +            m_pos = std::min(m_pos, ARRAYSIZE(m_message));
This `std::min` should be redundant considering the changed check above.

2017-08-18 19:58 UTC, YaLTeR commented on source/shared/ipc.h
> +            if (m_pos >= ARRAYSIZE(m_message) - length)
This should probably be `- length - sizeof(DWORD) * 2 - length padding`.

2017-08-18 19:58 UTC, YaLTeR commented on source/shared/ipc.h
> +            m_pos = std::min(m_pos, ARRAYSIZE(m_message));
Isn't this check redundant considering the check above?

2017-08-19 17:12 UTC, YaLTeR approved these changes

2017-08-19 17:28 UTC, Warepire commented
Don't merge yet, one of the static_asserts in the Alignment function is broken, it should test if the value is a power of 2, not just dividable by 2.

2017-08-19 17:38 UTC, Warepire commented
Ok, the new `static_assert` should do it. Please look at it and tell me what you think.

2017-08-19 17:57 UTC, YaLTeR commented
LGTM

2017-08-19 18:00 UTC, merged